import isAssetNameConnectedForWalletAccountSelectorDefinition from './isAssetNameConnectedForWalletAccount.js'

const hardwareWalletsSelectors = [isAssetNameConnectedForWalletAccountSelectorDefinition]

export default hardwareWalletsSelectors
