declare module '@exodus/storage-memory'
declare module '@exodus/dependency-injection'
declare module '@exodus/dependency-preprocessors'
declare module '@exodus/dependency-preprocessors/*'
declare module '@exodus/asset-lib'
declare module '@exodus/keychain/module/crypto/seed-id'
